appProperties:
  host.validation: false

datasourceProperties:
  db.username: 'fortify'
  db.password: 'fortify'
  db.driver.class: com.microsoft.sqlserver.jdbc.SQLServerDriver
  db.dialect: com.fortify.manager.util.hibernate.SQLServerDialect
  db.like.specialCharacters: '%_{'
  jdbc.url: 'jdbc:sqlserver://3.122.100.42:1433;database=ssc;sendStringParametersAsUnicode=false'
